server:
  port: 8001



spring:
  application:
    name: dept-provider-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    druid:
      min-idle: 5
      initial-size: 5
      max-active: 5
mybatis:
  type-aliases-package: com.gaoxiong.springcloud.entities         #别名
#  mapper-locations:
#    - classpath: mybatis/mapper/**/*.xml                            #映射文件
  configuration:
    cache-enabled: true #开启二级缓存
eureka:
  instance:
    hostname: dept8001provider
    instance-id: dept-8001-provider
    prefer-ip-address: true   #路径显示IP信息
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka-server7003:7003/eureka/,http://eureka-server7002:7002/eureka/,http://eureka-server7001:7001/eureka/
