server:
  port: 8001



spring:
  application:
    name: dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    druid:
      min-idle: 5
      initial-size: 5
      max-active: 5
mybatis:
  type-aliases-package: com.gaoxiong.springcloud.entities         #别名
#  mapper-locations:
#    - classpath: mybatis/mapper/**/*.xml                            #映射文件
  configuration:
    cache-enabled: true                                           #开启二级缓存