spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaoxiong523/microservicecloud-config.git
  application:
    name: microservicecloud-config
         # username: 公共仓库可以不用配置,实际生成环境必须要配置用户名和密码才能访问 github
         # password:
server:
  port: 3344