---
spring:
  profiles: eureka_server7001
  application:
    name: eureka-server7001
server:
  port: 7001
eureka:
  client:
    register-with-eureka: false #false表示不向服务中心注册自己,单注册中心要配置,
    fetch-registry: false #false 表示自己端就是注册中心,我的职责是维护服务实例,并不需要取检索服务
    service-url:
      defaultZone: http://eureka-server7003:7003/eureka/,http://eureka-server7002:7002/eureka/ #设置 与eureka server 交互的地址查询服务和注册服务
  instance:
    hostname: eureka-server7001  # eureka 服务端的实例名称



---
spring:
  profiles: eureka_server7002
  application:
    name: eureka-server7002
server:
  port: 7002
eureka:
  client:
    register-with-eureka: false #false表示不向服务中心注册自己,单注册中心要配置,
    fetch-registry: false #false 表示自己端就是注册中心,我的职责是维护服务实例,并不需要取检索服务
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka/,http://eureka-server7003:7003/eureka/ #设置 与eureka server 交互的地址查询服务和注册服务
  instance:
    hostname: eureka-server7002  # eureka 服务端的实例名称

---   #多个配置之间一定要用 三个短横线隔开
spring:
  profiles: eureka_server7003
  application:
    name: eureka-server7003
server:
  port: 7003
eureka:
  client:
    register-with-eureka: false #false表示不向服务中心注册自己,单注册中心要配置,
    fetch-registry: false #false 表示自己端就是注册中心,我的职责是维护服务实例,并不需要取检索服务
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka/,http://eureka-server7002:7002/eureka/ #设置 与eureka server 交互的地址查询服务和注册服务
  instance:
    hostname: eureka-server7003  # eureka 服务端的实例名称
