server:
  port: 8088
eureka:
  instance:
    hostname: dept-8088-consumer
    prefer-ip-address: true
    instance-id: dept-8088-consumer
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server7003:7003/eureka/,http://eureka-server7002:7002/eureka/,http://eureka-server7001:7001/eureka/
spring:
  application:
    name: dept-consumer-8088